apiDefinitions:
    PensionService: FRIDA_PensionInformation_OA3_full_en.yaml
referenceDocs:
  theme: {
    typography: {
      heading1: {
        transform: 'uppercase',
        },
      rightPanelHeading: {
        transform: 'uppercase'
        },
      fieldName: {
        fontWeight: 'bold'
        }
     }
    }