name: Deploy
on: [push]
jobs:
  build:
    name: Generate asciidoc and start Workflow of FRIDA-official/Antora-FRIDA-Playbook 
    runs-on: ubuntu-latest
    container: 
            image: antora/antora
    steps:
      - uses: actions/checkout@master
        with: 
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
          ref: ${{ github.ref }}
      - name: test npm
        run: npm --version
      - name: Workflow Dispatch
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: deploy documentation
          repo: FRIDA-official/Antora-FRIDA-Playbook
          token: ${{ secrets.G_ACCESS_TOKEN }}
         