name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Run Web App
    runs-on: ubuntu-latest
    steps:
      - name: Build Web App
        run: |
          echo "Build Web App"
      - name: Trigger shit
        uses: peter-evans/repository-dispatch@v1
        with:
          workflow: deploy.yml
          repo: FRIDA-offical/Antora-FRIDA-Playbook
          token: ${{ secrets.G_ACCESS_TOKEN }}
          inputs: '{ "message": "blah blah", "debug": true }'
      - name: Deploy Web App
        run: |
          echo "Deploy Web App"
          