name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Run Web App
    runs-on: ubuntu-latest
    steps:
      - name: Build Web App
        run: |
          echo "Build Web App"
      - name: Workflow Dispatch
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: deploy.yml 
          repo: FRIDA-official/Antora-FRIDA-Playbook
          token: ${{ secrets.G_ACCESS_TOKEN }}
          inputs: '{ "message": "blah blah", "debug": true }'
      - name: Deploy Web App
        run: |
          echo "Deploy Web App"
          