name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Run Web App
    runs-on: ubuntu-latest
    steps:
      - name: Build Web App
        run: |
          echo "Build Web App"
          
      - uses: peter-evans/repository-dispatch@v1
        with:
          repository: FRIDA-offical/Antora-FRIDA-Playbook
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          event-type: my-event
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
      - name: Deploy Web App
        run: |
          echo "Deploy Web App"
          