name: Deploy
# if there is a push on the Antora-PensionService repository
on: [push]
jobs:
    # Job which uses a docker image with pre installed programms 
    Generate_asciidoc_and_start_Workflow_of_Antora-FRIDA-Playbook:
      runs-on: ubuntu-latest
      container: 
          image: nathanfriend/java-node-git:8-slim
      steps:
        # Checkout the Antora-PensionService repository on the docker image
        - uses: actions/checkout@master
          with: 
            persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
            fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
            ref: ${{ github.ref }} 
        # Install openapi-cli 
        - name: install npm packages
          run: |
              npm install @openapitools/openapi-generator-cli -g     
        # Generate asciidoc files out of the yaml files              
        - name: validate yaml and generate asciidoc out of yaml spec
          if: hashFiles('*.yaml') != ''
          run: |        
              for filename in ./*.yaml; do openapi-generator-cli generate -g asciidoc -i $filename -o ./docs/modules/PensionService/pages/ ; done 
        # Add the generated yaml file
        - name: Add files 
          run: 
            git add ./docs/modules/PensionService/pages/index.adoc
        # Commit the generated file
        - name: Commit files
          run: | 
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git commit -a -m "Add changes" --allow-empty
        # Push Commits to the branch you are currently on and force the push    
        - name: Pushing changes to current Branch
          uses: ad-m/github-push-action@master          
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}
            force: true
        # Start the workflow of the Antora-FRIDA-Playbook            
        - name: Workflow Dispatch
          uses: benc-uk/workflow-dispatch@v1
          with:
            workflow: deploy documentation
            repo: FRIDA-official/Antora-FRIDA-Playbook
            token: ${{ secrets.G_ACCESS_TOKEN }}
         